##### EDA

In [2]:
import torchxrayvision as xrv

C:\Program Files\Python312\Lib\site-packages\torchxrayvision\utils.py:11: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import tqdm


In [3]:
d = xrv.datasets.COVID19_Dataset(imgpath="data/images/", csvpath="data/csv/metadata.csv")

In [4]:
img = d[0]['img'][0]
print(f"sample image of shape {img.shape}")
print(f"dataset of length {len(d)}")
print(img)

sample image of shape (888, 882)
dataset of length 535
[[1024.      1015.9686  1007.93726 ... -469.83527 -477.86664 -477.86664]
 [1024.      1024.      1015.9686  ... -493.92938 -493.92938 -493.92938]
 [1024.      1024.      1015.9686  ... -501.96075 -509.99213 -509.99213]
 ...
 [1024.      1024.       983.84314 ... -172.6745  -156.61176 -148.58038]
 [1024.      1024.       983.84314 ... -252.98822 -244.95685 -244.95685]
 [1024.      1024.       983.84314 ... -437.70978 -429.6784  -421.64703]]


##### Dataloader

In [4]:
from dataLoader import *
from torch.utils.data import DataLoader

In [2]:
train_dataset = Covid19DataSet(transform = ToTensor(), train = True)
test_dataset = Covid19DataSet(transform = ToTensor(), train = False)

Shape of X_train is (321, 1, 224, 224). Shape of ytrain is (321, 1)
Shape of X_test is (214, 1, 224, 224). Shape of ytest is (214, 1)


In [5]:
batch_size = 16
train_loader = DataLoader(dataset = train_dataset, batch_size = batch_size, shuffle = True)
test_loader = DataLoader(dataset = test_dataset, batch_size = batch_size, shuffle = True)

In [6]:
train_iter = iter(train_loader)
test_iter = iter(test_loader)

In [7]:
train_samples, train_labels = next(train_iter)
test_samples, test_labels = next(test_iter)
print(train_samples.shape, train_labels.shape, test_samples.shape, test_labels.shape)

torch.Size([16, 1, 224, 224]) torch.Size([16, 1]) torch.Size([16, 1, 224, 224]) torch.Size([16, 1])


##### Building of model

In [8]:
from models import *

In [10]:
model = ConvNet()

##### Training Model

In [11]:
epochs = 10
train_model(model, train_loader, epochs)

Training model...
Epoch [1/10], Loss: 0.6603
Epoch [2/10], Loss: 0.6583
Epoch [3/10], Loss: 0.6744
Epoch [4/10], Loss: 0.6472
Epoch [5/10], Loss: 0.6302
Epoch [6/10], Loss: 0.6279
Epoch [7/10], Loss: 0.6118
Epoch [8/10], Loss: 0.5791
Epoch [9/10], Loss: 0.6063
Epoch [10/10], Loss: 0.5853
Done!


##### Evaluation

In [12]:
evaluate_model(model, test_loader)

Precision: 0.677570093457944 . Recall: 1.0
