##### EDA

In [2]:
import torchxrayvision as xrv

C:\Program Files\Python312\Lib\site-packages\torchxrayvision\utils.py:11: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import tqdm


In [3]:
d = xrv.datasets.COVID19_Dataset(imgpath="data/images/", csvpath="data/csv/metadata.csv")

In [4]:
img = d[0]['img'][0]
print(f"sample image of shape {img.shape}")
print(f"dataset of length {len(d)}")
print(img)

sample image of shape (888, 882)
dataset of length 535
[[1024.      1015.9686  1007.93726 ... -469.83527 -477.86664 -477.86664]
 [1024.      1024.      1015.9686  ... -493.92938 -493.92938 -493.92938]
 [1024.      1024.      1015.9686  ... -501.96075 -509.99213 -509.99213]
 ...
 [1024.      1024.       983.84314 ... -172.6745  -156.61176 -148.58038]
 [1024.      1024.       983.84314 ... -252.98822 -244.95685 -244.95685]
 [1024.      1024.       983.84314 ... -437.70978 -429.6784  -421.64703]]


##### Dataloader

In [1]:
from dataLoader import *
from torch.utils.data import DataLoader

C:\Users\Hoo Kai Sng\OneDrive - National University of Singapore\Documents\NUS\CS3244\Project\xrayenv\Lib\site-packages\torchxrayvision\utils.py:11: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import tqdm


In [2]:
train_dataset = Covid19DataSet('train', transform = 'vanilla')
augmented_dataset = Covid19DataSet('train', transform = 'augment')
validation_dataset = Covid19DataSet('val', transform = 'vanilla')
test_dataset = Covid19DataSet('test', transform = 'vanilla')

In [3]:
BATCH_SIZE = 16
train_loader = DataLoader(dataset = train_dataset, batch_size = BATCH_SIZE, shuffle = True, num_workers = 4)
validation_loader = DataLoader(dataset = validation_dataset, batch_size = BATCH_SIZE, shuffle = False, num_workers = 4)
test_loader = DataLoader(dataset = test_dataset, batch_size = BATCH_SIZE, shuffle = False, num_workers = 4)

##### Building of model

In [4]:
from models import *

In [5]:
model_11 = ConvNet()

In [6]:
model_12 = ConvNet()

In [7]:
model_21 = ConvNetGlobPooling()

In [8]:
model_22 = ConvNetGlobPooling()

##### Training Model

In [11]:
from evaluation import *

In [12]:
# Training for a default of 25 epochs

In [13]:
train_model(model_21, train_loader, validation_loader)

Training model...
Epoch [1/5] | Metric Val: 0.7757 | Epoch Loss: 12.8016
Epoch [2/5] | Metric Val: 0.7757 | Epoch Loss: 12.3200
Epoch [3/5] | Metric Val: 0.7757 | Epoch Loss: 12.8012
Epoch [4/5] | Metric Val: 0.7757 | Epoch Loss: 12.3199
Epoch [5/5] | Metric Val: 0.7757 | Epoch Loss: 12.3201
Training completed in 9mins 27s
Best validation: 0.7757009345794392


ConvNetGlobPooling(
  (conv1): Conv2d(1, 8, kernel_size=(5, 5), stride=(1, 1))
  (pool): MaxPool2d(kernel_size=4, stride=4, padding=0, dilation=1, ceil_mode=False)
  (conv2): Conv2d(8, 16, kernel_size=(5, 5), stride=(1, 1))
  (global_avg_pool): AdaptiveAvgPool2d(output_size=1)
  (fc1): Linear(in_features=16, out_features=128, bias=True)
  (fc2): Linear(in_features=128, out_features=64, bias=True)
  (fc3): Linear(in_features=64, out_features=1, bias=True)
)

In [14]:
train_model(model_22, train_loader, validation_loader)

Training model...
Epoch [1/5] | Metric Val: 0.7757 | Epoch Loss: 12.7962
Epoch [2/5] | Metric Val: 0.7757 | Epoch Loss: 12.3128
Epoch [3/5] | Metric Val: 0.7757 | Epoch Loss: 12.3123
Epoch [4/5] | Metric Val: 0.7757 | Epoch Loss: 12.3127
Epoch [5/5] | Metric Val: 0.7757 | Epoch Loss: 12.3129
Training completed in 9mins 19s
Best validation: 0.7757009345794392


ConvNetGlobPooling(
  (conv1): Conv2d(1, 8, kernel_size=(5, 5), stride=(1, 1))
  (pool): MaxPool2d(kernel_size=4, stride=4, padding=0, dilation=1, ceil_mode=False)
  (conv2): Conv2d(8, 16, kernel_size=(5, 5), stride=(1, 1))
  (global_avg_pool): AdaptiveAvgPool2d(output_size=1)
  (fc1): Linear(in_features=16, out_features=128, bias=True)
  (fc2): Linear(in_features=128, out_features=64, bias=True)
  (fc3): Linear(in_features=64, out_features=1, bias=True)
)

##### Evaluation

In [15]:
metric_21_prec = evaluate_model(model_21, test_loader, 'prec') * 100
metric_21_rec = evaluate_model(model_21, test_loader, 'rec') * 100
print(f"model 2.1: Precision = {metric_21_prec:.0f}% | Recall = {metric_21_rec:.0f}%")

model 2.1: Precision = 78% | Recall = 100%


In [ ]:
metric_22_prec = evaluate_model(model_21, test_loader, 'prec') * 100
metric_22_rec = evaluate_model(model_22, test_loader, 'rec') * 100
print(f"model 2.2: Precision = {metric_21_prec:.0f}% | Recall = {metric_21_rec:.0f}%")